spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: detector-app
  artemis:
    embedded:
      enabled: false
    host: localhost
    port: 61616
    user: trafficmonitoring
    password: trafficmonitoring

equipment:
  mode: "STATEFUL"
  id: "ff5b0042-96f4-42e8-a79d-8f423e9df348"
  lng: 1
  lat: 2
  numberOfLanes: 2

api:
  url: "http://localhost:8080"